# Generated by Django 4.1.7 on 2023-02-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalApp', '0002_breed_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='createdat',
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Siting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalApp.animal')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalApp.breed')),
            ],
        ),
    ]
