# Generated by Django 4.1.7 on 2023-02-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalApp', '0004_alter_siting_animal_alter_siting_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siting',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalApp.animal'),
        ),
        migrations.AlterField(
            model_name='siting',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalApp.breed'),
        ),
    ]
